//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4335
{
    using System;
    using System.Collections.Generic;
    
    public partial class V
    {
        public int Code { get; set; }
        public string Position { get; set; }
        public string Login { get; set; }
    }
}
